{\rtf1\ansi \deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;
}{\f1\fnil\fcharset0\fprq2 Times New Roman;
}{\f2\fmodern\fcharset0\fprq1 Courier New;
}}{\colortbl;
\red0\green0\blue0;
\red0\green0\blue255;
\red0\green255\blue255;
\red0\green255\blue0;
\red255\green0\blue255;
\red255\green0\blue0;
\red255\green255\blue0;
\red255\green255\blue255;
\red0\green0\blue128;
\red0\green128\blue0;
\red128\green0\blue128;
\red128\green0\blue0;
\red128\green128\blue0;
\red128\green128\blue128;
\red192\green192\blue192;
}\hyphauto1\deflang1033
\marglsxn2070\margrsxn1080\margtsxn720\margbsxn1440\cols1\endnhere\colno1\colw9090\pard
\brdrb\brdrs\brdrw120\brdrcf1
\nowidctlpar\hyphpar0
\li-630\ri0\fi0
\ql\plain \b \f0
\fs26
\cf1
{Chapter 08: How to handle exceptions\par
}\plain \b \f0
\fs26
\cf1
{Murach's Python Programming (2nd Edition)}\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs36
\cf1
{\par
}\plain \f0
\fs36
\cf1
\pard
\nowidctlpar\hyphpar0
\li-630\ri0\fi0
\ql\plain \b \f0
\fs22
\cf1
{MULTIPLE CHOICE}\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs22
\cf1
{\par
}\plain \f0
\fs22
\cf1
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi-630
\ql\sa120\tqr\tx-180\tx0
{\tab }\plain \f0
\fs22
\cf1
{1.}{\tab }\plain \f0
\fs22
\cf1
{A Python program should use try statements to handle\par
}\plain \f0
\fs22
\cf1
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{a.}{\cell
}{all exceptions that might be thrown by a program\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{b.}{\cell
}{only the exceptions related to file and database I/O\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{c.}{\cell
}{all the exceptions that aren\'92
t caused by coding errors\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{d.}{\cell
}{all exceptions that can\'92
t be prevented by normal coding techniques\cell
}\row
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\sa1\plain \f0
\fs12
\cf1
{\par
}\plain \f0
\fs12
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\tx0\tx634\tx1958\tx2592\tx3916\tx4550\tx5874\tx6508
\plain \f0
\fs22
\cf1
{ANS:\tab }\plain \f0
\fs22
\cf1
{D}\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs22
\cf1
{\par
}\plain \f0
\fs22
\cf1
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi-630
\ql\sa120\tqr\tx-180\tx0
{\tab }\plain \f0
\fs22
\cf1
{2.}{\tab }\plain \f0
\fs22
\cf1
{Within the try clause of a try statement, you code\par
}\plain \f0
\fs22
\cf1
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{a.}{\cell
}{all the statements of the program\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{b.}{\cell
}{only the statements that might cause an exception\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{c.}{\cell
}{a block of statements that might cause an exception\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{d.}{\cell
}{a block of the statements that are most likely to cause an exception\cell
}\row
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\sa1\plain \f0
\fs12
\cf1
{\par
}\plain \f0
\fs12
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\tx0\tx634\tx1958\tx2592\tx3916\tx4550\tx5874\tx6508
\plain \f0
\fs22
\cf1
{ANS:\tab }\plain \f0
\fs22
\cf1
{C}\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs22
\cf1
{\par
}\plain \f0
\fs22
\cf1
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi-630
\ql\sa120\tqr\tx-180\tx0
{\tab }\plain \f0
\fs22
\cf1
{3.}{\tab }\plain \f0
\fs22
\cf1
{When an exception is thrown, Python creates an exception object that contains al
l but one of the following items of information. Which one is it?\par
}\plain \f0
\fs22
\cf1
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{a.}{\cell
}{the type of exception\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{b.}{\cell
}{the name of the class for the type of exception\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{c.}{\cell
}{the severity of the exception\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{d.}{\cell
}{the message for the exception\cell
}\row
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\sa1\plain \f0
\fs12
\cf1
{\par
}\plain \f0
\fs12
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\tx0\tx634\tx1958\tx2592\tx3916\tx4550\tx5874\tx6508
\plain \f0
\fs22
\cf1
{ANS:\tab }\plain \f0
\fs22
\cf1
{C}\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs22
\cf1
{\par
}\plain \f0
\fs22
\cf1
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi-630
\ql\sa120\tqr\tx-180\tx0
{\tab }\plain \f0
\fs22
\cf1
{4.}{\tab }\plain \f0
\fs22
\cf1
{To cancel the execution of a program in the catch clause of a try statement, you
 can use the \par
}\plain \f0
\fs22
\cf1
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx4185
\clvertalt
\cellx4545
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{a.}{\cell
}{cancel() function of the sys module\cell
}{c.}{\cell
}{the built-in cancel() function\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx4185
\clvertalt
\cellx4545
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{b.}{\cell
}{exit() function of the sys module\cell
}{d.}{\cell
}{the built-in exit() function\cell
}\row
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\sa1\plain \f0
\fs12
\cf1
{\par
}\plain \f0
\fs12
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\tx0\tx634\tx1958\tx2592\tx3916\tx4550\tx5874\tx6508
\plain \f0
\fs22
\cf1
{ANS:\tab }\plain \f0
\fs22
\cf1
{B}\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs22
\cf1
{\par
}\plain \f0
\fs22
\cf1
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi-630
\ql\sa120\tqr\tx-180\tx0
{\tab }\plain \f0
\fs22
\cf1
{5.}{\tab }\plain \f0
\fs22
\cf1
{The finally clause of a try statement\par
}\plain \f0
\fs22
\cf1
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{a.}{\cell
}{is required\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{b.}{\cell
}{is executed whether or not an exception has been thrown\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{c.}{\cell
}{can be used to display more information about an exception\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{d.}{\cell
}{can be used to recover from an exception\cell
}\row
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\sa1\plain \f0
\fs12
\cf1
{\par
}\plain \f0
\fs12
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\tx0\tx634\tx1958\tx2592\tx3916\tx4550\tx5874\tx6508
\plain \f0
\fs22
\cf1
{ANS:\tab }\plain \f0
\fs22
\cf1
{B}\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs22
\cf1
{\par
}\plain \f0
\fs22
\cf1
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi-630
\ql\sa120\tqr\tx-180\tx0
{\tab }\plain \f0
\fs22
\cf1
{6.}{\tab }\plain \f0
\fs22
\cf1
{To throw an exception with Python code, you use the \par
}\plain \f0
\fs22
\cf1
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{a.}{\cell
}{throw statement\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{b.}{\cell
}{raise statement\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{c.}{\cell
}{built-in throw() function\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{d.}{\cell
}{build-in raise() function\cell
}\row
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\sa1\plain \f0
\fs12
\cf1
{\par
}\plain \f0
\fs12
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\tx0\tx634\tx1958\tx2592\tx3916\tx4550\tx5874\tx6508
\plain \f0
\fs22
\cf1
{ANS:\tab }\plain \f0
\fs22
\cf1
{B}\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs22
\cf1
{\par
}\plain \f0
\fs22
\cf1
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi-630
\ql\sa120\tqr\tx-180\tx0
{\tab }\plain \f0
\fs22
\cf1
{7.}{\tab }\plain \f0
\fs22
\cf1
{It\'92
s a common practice to throw your own exceptions to test error handling routi
nes that\par
}\plain \f0
\fs22
\cf1
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{a.}{\cell
}{provide for many different types of exceptions\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{b.}{\cell
}{catch exceptions that are hard to produce otherwise\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{c.}{\cell
}{handle many varieties of input\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{d.}{\cell
}{handle complexities like lists within lists\cell
}\row
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\sa1\plain \f0
\fs12
\cf1
{\par
}\plain \f0
\fs12
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\tx0\tx634\tx1958\tx2592\tx3916\tx4550\tx5874\tx6508
\plain \f0
\fs22
\cf1
{ANS:\tab }\plain \f0
\fs22
\cf1
{B}\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs22
\cf1
{\par
}\plain \f0
\fs22
\cf1
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi-630
\ql\sa120\tqr\tx-180\tx0
{\tab }\plain \f0
\fs22
\cf1
{8.}{\tab }\plain \f0
\fs22
\cf1
{If }\plain \f1
\fs22
\cf1
{a program attempts to read from a file that does not exist, which of the followi
ng will catch that error? \par
}\plain \f0
\fs22
\cf1
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx4185
\clvertalt
\cellx4545
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{a.}{\cell
}{FileNotFoundError and ValueError\cell
}{c.}{\cell
}\pard
\intbl \widctlpar\keep\hyphpar0
\li360\ri0\fi-360
\ql{FileNotFoundError and OSError\cell
}\row
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx4185
\clvertalt
\cellx4545
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{b.}{\cell
}\pard
\intbl \widctlpar\keep\hyphpar0
\li360\ri0\fi-360
\ql{FileNotFoundError and NameError\cell
}\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{d.}{\cell
}\pard
\intbl \widctlpar\keep\hyphpar0
\li360\ri0\fi-360
\ql{NameError and OSError\cell
}\row
\pard
\widctlpar\keep\hyphpar0
\li360\ri0\fi-360
\ql\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\sa1\plain \f0
\fs12
\cf1
{\par
}\plain \f0
\fs12
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\tx0\tx634\tx1958\tx2592\tx3916\tx4550\tx5874\tx6508
\plain \f0
\fs22
\cf1
{ANS:\tab }\plain \f0
\fs22
\cf1
{C}\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs22
\cf1
{\par
}\plain \f0
\fs22
\cf1
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi-630
\ql\sa120\tqr\tx-180\tx0
{\tab }\plain \f0
\fs22
\cf1
{9.}{\tab }\plain \f0
\fs22
\cf1
{Which of the following is the correct way to code a try statement that catches a
ny type of exception that can occur in the try clause?\par
}\plain \f0
\fs22
\cf1
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{a.}{\cell
}\plain \b \f2
\fs18
\cf1
{try:\par
}\plain \b \f2
\fs18
\cf1
{    number = float(input("Enter a number: "))\par
}\plain \b \f2
\fs18
\cf1
{    print("Your number is: ", number)\par
}\plain \b \f2
\fs18
\cf1
{except:\par
}\plain \b \f2
\fs18
\cf1
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\sa120{     print("Invalid number.")\cell
}\row
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs22
\cf1
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{b.}{\cell
}\plain \b \f2
\fs18
\cf1
{try:\par
}\plain \b \f2
\fs18
\cf1
{    number = float(input("Enter a number: "))\par
}\plain \b \f2
\fs18
\cf1
{    print("Your number is: ", number)\par
}\plain \b \f2
\fs18
\cf1
{except ValueError:\par
}\plain \b \f2
\fs18
\cf1
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\sa120{     print("Invalid number.")}\plain \f0
\fs22
\cf1
{\cell
}\row
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{c.}{\cell
}\plain \b \f2
\fs18
\cf1
{try:\par
}\plain \b \f2
\fs18
\cf1
{    number = float(input("Enter a number: "))\par
}\plain \b \f2
\fs18
\cf1
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\sa120{    print("Your number is: ", number)}\plain \f0
\fs22
\cf1
{\cell
}\row
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{d.}{\cell
}\plain \b \f2
\fs18
\cf1
{try:\par
}\plain \b \f2
\fs18
\cf1
{    number = float(input("Enter a number: "))\par
}\plain \b \f2
\fs18
\cf1
{    print("Your number is: ", number)\par
}\plain \b \f2
\fs18
\cf1
{else:\par
}\plain \b \f2
\fs18
\cf1
{     print("Invalid number.")}\plain \f0
\fs22
\cf1
{\cell
}\row
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\sa1\plain \f0
\fs12
\cf1
{\par
}\plain \f0
\fs12
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\tx0\tx634\tx1958\tx2592\tx3916\tx4550\tx5874\tx6508
\plain \f0
\fs22
\cf1
{ANS:\tab }\plain \f0
\fs22
\cf1
{A}\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs22
\cf1
{\par
}\plain \f0
\fs22
\cf1
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi-630
\ql\sa120\tqr\tx-180\tx0
{\tab }\plain \f0
\fs22
\cf1
{10.}{\tab }\plain \f0
\fs22
\cf1
{Which of the following is the correct way to code a try statement that displays 
the type and message of the exception that\'92
s caught?\par
}\plain \f0
\fs22
\cf1
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{a.}{\cell
}\plain \b \f2
\fs18
\cf1
{try:\par
}\plain \b \f2
\fs18
\cf1
{    number = int(input("Enter a number: "))\par
}\plain \b \f2
\fs18
\cf1
{    print("Your number is: ", number)\par
}\plain \b \f2
\fs18
\cf1
{except Exception as e:\par
}\plain \b \f2
\fs18
\cf1
{    print(e(type), e(message))\cell
}\row
\plain \f0
\fs22
\cf1
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{b.}{\cell
}\plain \b \f2
\fs18
\cf1
{try:\par
}\plain \b \f2
\fs18
\cf1
{    number = int(input("Enter a number: "))\par
}\plain \b \f2
\fs18
\cf1
{    print("Your number is: ", number)\par
}\plain \b \f2
\fs18
\cf1
{except Exception as e:\par
}\plain \b \f2
\fs18
\cf1
{    print(type(e), e)}\plain \f0
\fs22
\cf1
{\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{c.}{\cell
}\plain \b \f2
\fs18
\cf1
{try:\par
}\plain \b \f2
\fs18
\cf1
{    number = int(input("Enter a number: "))\par
}\plain \b \f2
\fs18
\cf1
{    print("Your number is: ", number)\par
}\plain \b \f2
\fs18
\cf1
{except Exception:\par
}\plain \b \f2
\fs18
\cf1
{     print(Exception(type), Exception(message))}\plain \f0
\fs22
\cf1
{\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{d.}{\cell
}\plain \b \f2
\fs18
\cf1
{try:\par
}\plain \b \f2
\fs18
\cf1
{    number = int(input("Enter a number: "))\par
}\plain \b \f2
\fs18
\cf1
{    print("Your number is: ", number)\par
}\plain \b \f2
\fs18
\cf1
{except Exception:\par
}\plain \b \f2
\fs18
\cf1
{     print(type(Exception), Exception)}\plain \f0
\fs22
\cf1
{\cell
}\row
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\sa1\plain \f0
\fs12
\cf1
{\par
}\plain \f0
\fs12
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\tx0\tx634\tx1958\tx2592\tx3916\tx4550\tx5874\tx6508
\plain \f0
\fs22
\cf1
{ANS:\tab }\plain \f0
\fs22
\cf1
{B}\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs22
\cf1
{\par
}\plain \f0
\fs22
\cf1
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\sa120\plain \b \f0
\fs22
\cf1
{Code Example 8-1\par
}\plain \b \f0
\fs22
\cf1
\pard
\widctlpar\keep\hyphpar0
\li360\ri0\fi0
\ql\plain \b \f2
\fs18
\cf1
{import csv\par
}\plain \b \f2
\fs18
\cf1
\pard
\widctlpar\keep\hyphpar0
\li360\ri0\fi0
\ql\sa120{import sys\par
}\plain \b \f2
\fs18
\cf1
{FILENAME = "names.csv"\par
}\plain \b \f2
\fs18
\cf1
\pard
\widctlpar\keep\hyphpar0
\li360\ri0\fi0
\ql{def main():\par
}\plain \b \f2
\fs18
\cf1
{    try:\par
}\plain \b \f2
\fs18
\cf1
{        names = []\par
}\plain \b \f2
\fs18
\cf1
{        with open(FILENAME, newline="") as file:\par
}\plain \b \f2
\fs18
\cf1
{            reader = csv.reader(file)\par
}\plain \b \f2
\fs18
\cf1
{            for row in reader:\par
}\plain \b \f2
\fs18
\cf1
{                names.append(row)\par
}\plain \b \f2
\fs18
\cf1
{    except FileNotFoundError as e:\par
}\plain \b \f2
\fs18
\cf1
{        print(f"Could not find \{FILENAME\} file.")\par
}\plain \b \f2
\fs18
\cf1
{        sys.exit()\par
}\plain \b \f2
\fs18
\cf1
{    except Exception as e:\par
}\plain \b \f2
\fs18
\cf1
{        print(type(e), e)\par
}\plain \b \f2
\fs18
\cf1
{        sys.exit()\par
}\plain \b \f2
\fs18
\cf1
\pard
\widctlpar\keep\hyphpar0
\li360\ri0\fi0
\ql\sa120{    print(names)       \par
}\plain \b \f2
\fs18
\cf1
\pard
\widctlpar\keep\hyphpar0
\li360\ri0\fi0
\ql{if __name__ == "__main__":\par
}\plain \b \f2
\fs18
\cf1
{    main()}\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs22
\cf1
{\par
}\plain \f0
\fs22
\cf1
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi-630
\ql\sa120\tqr\tx-180\tx0
{\tab }\plain \f0
\fs22
\cf1
{11.}{\tab }\plain \f0
\fs22
\cf1
{Refer to }\plain \b \f0
\fs22
\cf1
{Code Example 8-1}\plain \f0
\fs22
\cf1
{. If the names.csv file is not in the same directory as the file that contains t
he Python code, what type of exception will be thrown and caught?\par
}\plain \f0
\fs22
\cf1
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx4185
\clvertalt
\cellx4545
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{a.}{\cell
}{Exception \cell
}{c.}{\cell
}{FileNotFoundError\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx4185
\clvertalt
\cellx4545
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{b.}{\cell
}{OSError\cell
}{d.}{\cell
}{All of the above\cell
}\row
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\sa1\plain \f0
\fs12
\cf1
{\par
}\plain \f0
\fs12
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\tx0\tx634\tx1958\tx2592\tx3916\tx4550\tx5874\tx6508
\plain \f0
\fs22
\cf1
{ANS:\tab }\plain \f0
\fs22
\cf1
{C}\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs22
\cf1
{\par
}\plain \f0
\fs22
\cf1
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi-630
\ql\sa120\tqr\tx-180\tx0
{\tab }\plain \f0
\fs22
\cf1
{12.}{\tab }\plain \f0
\fs22
\cf1
{Refer to }\plain \b \f0
\fs22
\cf1
{Code Example 8-1}\plain \f0
\fs22
\cf1
{. If the for statement in the try clause refers to readers instead of reader, wh
at type exception will be thrown and caught?\par
}\plain \f0
\fs22
\cf1
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx4185
\clvertalt
\cellx4545
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{a.}{\cell
}{Exception \cell
}{c.}{\cell
}{NameError\cell
}\row
\trowd \trql\trgaph45\trleft-45\trautofit1
\clvertalt
\cellx315
\clvertalt
\cellx4185
\clvertalt
\cellx4545
\clvertalt
\cellx8415
\pard
\intbl \widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql{b.}{\cell
}{SyntaxError\cell
}{d.}{\cell
}{ReferenceError\cell
}\row
\pard
\widctlpar\keep\hyphpar0
\li0\ri0\fi0
\ql\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\plain \f0
\fs2
\cf1
{\par
}\plain \f0
\fs2
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\sa1\plain \f0
\fs12
\cf1
{\par
}\plain \f0
\fs12
\cf1
\pard
\nowidctlpar\hyphpar0
\li0\ri0\fi0
\ql\tx0\tx634\tx1958\tx2592\tx3916\tx4550\tx5874\tx6508
\plain \f0
\fs22
\cf1
{ANS:\tab }\plain \f0
\fs22
\cf1
{C\par
\pard
}}